 const CartActionTypes = {
 TOGGLE_CART_HIDDEN:'TOGGLE_CART_HIDDEN',
 Add_CART_ITEMS:'ADD_CART_ITEMS',
 CLEAR_CART_ITEMS: 'CLEAR_CART_ITEMS',
 REMOVE_CART_ITEMS: 'REMOVE_CART_ITEMS'
}

export default CartActionTypes;